name: passwordvaultclient
description: Password Vault Client.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  biometric: ^0.0.9
  encrypt: ^3.3.1
  shared_preferences: ^0.5.3+4
  path_provider: ^1.4.0

dev_dependencies:
  test: ^1.8.0

flutter:
  uses-material-design: true
  fonts:
      - family: RobotoMono
        fonts:
          - asset: fonts/RobotoMono-Regular.ttf